spring.datasource.url=jdbc:h2:mem:appecologica;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

server.port=8080

# JWT
app.jwt.secret=4d3a14562a9940f88b2c04d1cf78bd19f40dcb2f7f2d6046f0a7c9b98462a1bf
app.jwt.expiration-minutes=120

# Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
