spring.datasource.url=jdbc:mysql://127.0.0.1:3306/appecologica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

# H2 console deshabilitada al usar MySQL
spring.h2.console.enabled=false

# JWT
app.jwt.secret=4d3a14562a9940f88b2c04d1cf78bd19f40dcb2f7f2d6046f0a7c9b98462a1bf
app.jwt.expiration-minutes=120

# Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
