export const regiones = [
  { value: 'RM', label: 'Región Metropolitana' },
  { value: 'I', label: 'Tarapacá' },
  { value: 'II', label: 'Antofagasta' },
  { value: 'III', label: 'Atacama' },
  { value: 'IV', label: 'Coquimbo' },
  { value: 'V', label: 'Valparaíso' },
  { value: 'VI', label: "O'Higgins" },
  { value: 'VII', label: 'Maule' },
  { value: 'VIII', label: 'Biobío' },
  { value: 'IX', label: 'La Araucanía' },
  { value: 'X', label: 'Los Lagos' },
  { value: 'XI', label: 'Aysén' },
  { value: 'XII', label: 'Magallanes' },
  { value: 'XIV', label: 'Los Ríos' },
  { value: 'XV', label: 'Arica y Parinacota' },
  { value: 'XVI', label: 'Ñuble' },
]

export const comunasPorRegion: Record<string, string[]> = {
  RM: ['Santiago', 'Cerrillos', 'Cerro Navia', 'Conchalí', 'El Bosque', 'Estación Central', 'Huechuraba', 'Independencia', 'La Cisterna', 'La Florida', 'La Granja', 'La Pintana', 'La Reina', 'Las Condes', 'Lo Barnechea', 'Lo Espejo', 'Lo Prado', 'Macul', 'Maipú', 'Ñuñoa', 'Pedro Aguirre Cerda', 'Peñalolén', 'Providencia', 'Pudahuel', 'Quilicura', 'Quinta Normal', 'Recoleta', 'Renca', 'San Joaquín', 'San Miguel', 'San Ramón', 'Vitacura', 'Colina', 'Lampa', 'Til Til', 'Puente Alto', 'Pirque', 'San José de Maipo', 'Buin', 'Calera de Tango', 'Paine', 'San Bernardo', 'Alhué', 'Curacaví', 'María Pinto', 'Melipilla', 'San Pedro', 'Talagante', 'El Monte', 'Isla de Maipo', 'Padre Hurtado', 'Peñaflor'],
  I: ['Iquique', 'Alto Hospicio', 'Pozo Almonte', 'Camiña', 'Colchane', 'Huara', 'Pica'],
  II: ['Antofagasta', 'Calama', 'Tocopilla', 'Mejillones', 'Ollagüe', 'San Pedro de Atacama', 'Sierra Gorda', 'Taltal', 'María Elena'],
  III: ['Copiapó', 'Vallenar', 'Caldera', 'Chañaral', 'Diego de Almagro', 'Alto del Carmen', 'Freirina', 'Huasco', 'Tierra Amarilla'],
  IV: ['La Serena', 'Coquimbo', 'Ovalle', 'Illapel', 'Vicuña', 'Andacollo', 'Combarbalá', 'Monte Patria', 'Punitaqui', 'Río Hurtado', 'Canela', 'Los Vilos', 'Salamanca'],
  V: ['Valparaíso', 'Viña del Mar', 'Concón', 'Quilpué', 'Villa Alemana', 'San Antonio', 'Los Andes', 'San Felipe', 'Quillota', 'La Calera', 'Limache', 'Olmué', 'Casablanca', 'Juan Fernández', 'Algarrobo', 'Cartagena', 'El Quisco', 'El Tabo', 'Santo Domingo', 'Calle Larga', 'Rinconada', 'San Esteban', 'Catemu', 'Llaillay', 'Panquehue', 'Putaendo', 'Santa María', 'Hijuelas', 'La Cruz', 'Nogales', 'Cabildo', 'La Ligua', 'Papudo', 'Petorca', 'Zapallar', 'Isla de Pascua'],
  VI: ['Rancagua', 'San Fernando', 'Rengo', 'Machalí', 'Graneros', 'Codegua', 'Doñihue', 'Coltauco', 'Coínco', 'Las Cabras', 'Peumo', 'Pichidegua', 'San Vicente', 'Requínoa', 'Olivar', 'Malloa', 'Quinta de Tilcoco', 'Pichilemu', 'Navidad', 'Litueche', 'La Estrella', 'Marchihue', 'Paredones', 'Nancagua', 'Chimbarongo', 'Lolol', 'Pumanque', 'Santa Cruz', 'Palmilla', 'Peralillo', 'Placilla', 'Chépica'],
  VII: ['Talca', 'Curicó', 'Linares', 'Constitución', 'Molina', 'San Javier', 'Cauquenes', 'Parral', 'San Clemente', 'Pelarco', 'Río Claro', 'Maule', 'San Rafael', 'Teno', 'Romeral', 'Rauco', 'Sagrada Familia', 'Hualañé', 'Licantén', 'Vichuquén', 'Colbún', 'Longaví', 'Retiro', 'Villa Alegre', 'Yerbas Buenas', 'Chanco', 'Pelluhue', 'Empedrado', 'Pencahue', 'San Juan de Río'],
  VIII: ['Concepción', 'Talcahuano', 'Chiguayante', 'San Pedro de la Paz', 'Hualpén', 'Coronel', 'Lota', 'Tomé', 'Penco', 'Hualqui', 'Florida', 'Santa Juana', 'Arauco', 'Lebu', 'Curanilahue', 'Cañete', 'Contulmo', 'Tirúa', 'Los Álamos', 'Los Ángeles', 'Laja', 'Nacimiento', 'Cabrero', 'Yumbel', 'San Rosendo', 'Santa Bárbara', 'Quillaco', 'Mulchén', 'Quilleco', 'Antuco', 'Tucapel', 'Alto Biobío', 'Chillán', 'Chillán Viejo'],
  IX: ['Temuco', 'Padre Las Casas', 'Angol', 'Villarrica', 'Pucón', 'Lautaro', 'Nueva Imperial', 'Carahue', 'Freire', 'Cunco', 'Pitrufquén', 'Gorbea', 'Toltén', 'Teodoro Schmidt', 'Saavedra', 'Puerto Saavedra', 'Loncoche', 'Curarrehue', 'Melipeuco', 'Perquenco', 'Galvarino', 'Cholchol', 'Traiguén', 'Victoria', 'Curacautín', 'Lonquimay', 'Collipulli', 'Ercilla', 'Purén', 'Los Sauces', 'Lumaco', 'Tirúa'],
  X: ['Puerto Montt', 'Osorno', 'Castro', 'Ancud', 'Puerto Varas', 'Llanquihue', 'Frutillar', 'Fresia', 'Los Muermos', 'Maullín', 'Calbuco', 'Cochamó', 'Purranque', 'Río Negro', 'San Juan de la Costa', 'San Pablo', 'Quellón', 'Dalcahue', 'Chonchi', 'Queilén', 'Quinchao', 'Curaco de Vélez', 'Puqueldón', 'Hualaihué', 'Chaitén', 'Futaleufú', 'Palena'],
  XI: ['Coyhaique', 'Puerto Aysén', 'Chile Chico', 'Cochrane', 'Río Ibáñez', 'Lago Verde', 'Tortel', 'O´Higgins', 'Villa O´Higgins', 'Guaitecas', 'Cisnes'],
  XII: ['Punta Arenas', 'Puerto Natales', 'Porvenir', 'San Gregorio', 'Río Verde', 'Laguna Blanca', 'Primavera', 'Timaukel', 'Navarino', 'Cabo de Hornos', 'Antártica'],
  XIV: ['Valdivia', 'La Unión', 'Río Bueno', 'Paillaco', 'Panguipulli', 'Los Lagos', 'Máfil', 'Mariquina', 'Lanco', 'Corral', 'Futrono', 'Lago Ranco'],
  XV: ['Arica', 'Camarones', 'Putre', 'General Lagos'],
  XVI: ['Chillán', 'Chillán Viejo', 'Bulnes', 'Quillón', 'Yungay', 'Pemuco', 'El Carmen', 'Pinto', 'San Ignacio', 'Ñiquén', 'San Carlos', 'San Nicolás', 'Cobquecura', 'Quirihue', 'Ninhue', 'Treguaco', 'Coelemu', 'Portezuelo', 'Ránquil', 'San Fabián'],
}
